---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: phantserver
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: data.crookster.org
    http:
      paths:
      - path: /
        backend:
          serviceName: phantserver
          servicePort: phant-http
