---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: phantserver-persistent-volume
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /nfs_phant_data
    server: 192.168.50.12
