---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phant
  name: phantserver
spec:
  ports:
  - name: phant-http
    port: 8888
    targetPort: 8888
  - name: phant-telnet
    port: 8889
    targetPort: 8889
  selector:
    app: phant
    task: server
