# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: tinyauth

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyauth
  labels:
    app: tinyauth
  #namespace: tinyauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyauth
  template:
    metadata:
      labels:
        app: tinyauth
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: tinyauth
          image: ghcr.io/tinyauthapp/tinyauth:v5.0.7
          ports:
            - containerPort: 3000
              name: tinyauth-cip
              protocol: TCP            
          volumeMounts:
            - mountPath: "/authfile"
              name: "authfile"
            - mountPath: "/data"
              name: "session-db"
          env:
            # Log level (trace, debug, info, warn, error, fatal, panic)
            - name: "TINYAUTH_LOG_LEVEL"
              value: "trace"
              # value: "info"
            - name: TINYAUTH_APPURL
              value: "https://tinyauth.idcrook.dev"
            - name: TINYAUTH_AUTH_USERSFILE
              value: "/authfile/users.txt"
            - name: TINYAUTH_AUTH_TRUSTEDPROXIES
              value: "192.168.50.9,10.43.0.0/16"
          # livenessProbe:
          #   httpGet:
          #     path: /api/healthz
          #     port: tinyauth-cip
          # readinessProbe:
          #   httpGet:
          #     path: /api/healthz
          #     port: tinyauth-cip
      volumes:
          - name: authfile
            configMap:
              name: tinyauth-users-file
          - name: session-db
            # effectively: resets each restart
            emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tinyauth-svc
  #namespace: tinyauth
spec:
  #clusterIP: 10.43.164.234
  ports:
    - name: tinyauth-cip
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: tinyauth
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: tinyauth-middleware
    #namespace: tinyauth
spec:
    forwardAuth:
        # 
        #address: http://tinyauth-svc.default.svc.cluster.local:3000/api/auth/traefik
        address: http://tinyauth-svc:3000/api/auth/traefik
        #address: http://10.43.164.234:3000/api/auth/traefik
        maxResponseBodySize: 1048576
        trustForwardHeader: true 
        authResponseHeaders:
            # - Authorization
            # - X-Forwarded-User        
            - remote-user
            - remote-groups
            - remote-email
            - remote-name
# to use this middleware from default namespace
#         - name: tinyauth-middleware
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-tinyauth

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tinyauth.idcrook.dev`)
      services:
        - name: tinyauth-svc
          #namespace: tinyauth
          port: 3000
  tls:
    certResolver: wildcardresolver