---
# https://tinyauth.app/docs/getting-started#installation
# openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32 && echo
# 
# https://github.com/steveiliop56/tinyauth/issues/6#issuecomment-2613291472
# echo -n 'your-generated-secret-abcdefghia' | base64
#  - secretKey needs to be exactly 32 characters long
#
# docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v3 user create --interactive
#  echo -n 'result' | base64
apiVersion: v1
data:
  secretKey: <base64 of generated secret>
  USERS: |
    <multi-line base64 of
    .. full users list>
kind: Secret
metadata:
  name: tinyauth
  namespace: tinyauth
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  tinyauth-users
  namespace: tinyauth

# docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v3 user create --interactive
data:
  users.txt: |
    username:$$2a$$10$$r5IhodpqhTO5jt92vU94ieI26Zq9AENRn7J1ksWox7.z/jS48ts8.
    user:$$2a$$10$$llHiU28O6SBCauxYd9RAlexY6tGVeY8Otjof5BlvehzlRxrvaPyEO

