---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lighttpd-persistent-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    server: 10.0.1.10
    path: /nfs_static_www
