---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-lighttpd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      # .dev domains are now pre-loaded HSTS in most browsers so no redirect is done
      ##match: Host(`crookster.org`, `www.crookster.org`) || Host(`idcrook.com`, `www.idcrook.com`)
      match: Host(`crookster.org`, `www.crookster.org`)
      services:
        - name: lighttpd
          port: 80
      middlewares:
        - name: redirect-to-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-lighttpd

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`crookster.org`, `www.crookster.org`)
      services:
        - name: lighttpd
          port: 80
      # middlewares:
      #   - name: my-fail2ban
  tls:
    certResolver: myresolver

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-dev-lighttpd

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      # match: HostRegexp(`idcrook.dev`, `{subdomain:[-a-z0-9]+}\.idcrook\.dev`)
      match: Host(`idcrook.dev`, `www.idcrook.dev`)
      services:
        - name: lighttpd
          port: 80
      # middlewares:
      #   - name: my-fail2ban
  tls:
    certResolver: wildcardresolver
    domains:
      - main: idcrook.dev
        sans:
          -  "*.idcrook.dev"
