---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-lighttpd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`www.crookster.org`, `crookster.org`, `www.idcrook.com`, `idcrook.com`, `www.idcrook.dev`, `idcrook.dev`)
      services:
        - name: lighttpd
          port: 80
      middlewares:
        - name: redirect-to-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-lighttpd

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`www.crookster.org`, `crookster.org`, `www.idcrook.com`, `idcrook.com`, `www.idcrook.dev`, `idcrook.dev`)
      services:
        - name: lighttpd
          port: 80
  tls:
    certResolver: myresolver
