---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-lighttpd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`crookster.org`, `www.crookster.org`) || Host(`idcrook.com`, `www.idcrook.com`)
      services:
        - name: lighttpd
          port: 80
      middlewares:
        - name: redirect-to-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-lighttpd

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`crookster.org`, `www.crookster.org`) || Host(`idcrook.com`, `www.idcrook.com`) || HostRegexp(`idcrook.dev`, `{subdomain:[-a-z0-9]+}.idcrook.dev`)
      services:
        - name: lighttpd
          port: 80
  tls:
    certResolver: myresolver
    domains:
      - main: idcrook.dev
        sans:
          -  "*.idcrook.dev"
