---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-homeassistant-http

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ha.idcrook.dev`)
      services:
        - name: homeassistant-svc
          port: 8123
      # middlewares:
      #   - name: my-fail2ban
  tls: {}
