---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hedgedoc-persistent-volume
spec:
  capacity:
    storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /nfs_hedgedoc_data
    server: 192.168.50.12
