---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ntfy
  name: ntfy-pvc
  annotations:
    nfs.io/storage-path: ntfy
spec:
  storageClassName: nfs-client
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
