---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: forgejo
  name: forgejo-pvc
  # namespace: forgejo
  annotations:
    nfs.io/storage-path: forgejo
spec:
  storageClassName: nfs-client
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
