---  # -*- yaml -*-
# echo    conf/forgejo/forgejo-secrets.yaml >> .git/info/exclude
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
data:
  # DB_PASSWORD="xxx"
  # echo -n "$DB_PASSWORD" | base64
  FORGEJO__database__PASSWD: |
    eHh4
