---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trillium-persistent-volume
spec:
  capacity:
    storage: 2000Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /nfs_trillium_data
    server: 192.168.50.13

