---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: partytime-persistent-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    server: 192.168.50.13
    path: /nfs_partytime
