---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: partytime-persistent-claim
spec:
  storageClassName: slow
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
