---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-partytime
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`party.crookster.org`, `parties.crookster.org`)
      services:
        - name: partytime
          port: 80
      middlewares:
        - name: redirect-to-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-partytime

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`party.crookster.org`, `parties.crookster.org`)
      services:
        - name: partytime
          port: 80
  tls:
    certResolver: myresolver

