---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: gitea-app-custom-values
stringData:
  moreValues: |-
    database:
      address: db.example.com
      username: user
      password: pass
  someValues: |-
    adminUser:
      create: true
      username: admin
      password: secret