---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-persistent-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
