---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dex
spec:
#  type: NodePort
  ports:
  - name: dex
    port: 5556
    protocol: TCP
#    targetPort: 5556
#    nodePort: 32000
  selector:
    app: dex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
