---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-persistent-claim
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
