---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: inlets
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inlets
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: inlets
        #image: alexellis2/inlets:2.0.2-arm64
        image: dpcrook/inlets:latest
        imagePullPolicy: Always
        command: ["inlets"]
        args:
        - "client"
        - "--upstream=http://gateway.openfaas:8080"
        - "--remote=$(INLETS_SERVER_PROTOCOL)://$(INLETS_SERVER_IP_ADDR)"
        - "--token=$(INLETS_TOKEN)"
        env:
        - name: INLETS_SERVER_PROTOCOL
          value: wss
        - name: INLETS_SERVER_IP_ADDR
          valueFrom:
            secretKeyRef:
              name: inlets-secret
              key: INLETS_SERVER_IP_ADDR
        - name: INLETS_TOKEN
          valueFrom:
            secretKeyRef:
              name: inlets-secret
              key: INLETS_TOKEN
